### ISSUE TITLE
Will zkeme80 run on TI 84 Plus CE?

### ISSUE THREAD

**Issue by dfoderick** [siraben/zkeme80#4]
I love this project.
Will it run on the TI 84 Plus CE?
Basically, which TI models will it run on?

**Comment by siraben** [comment]
Hi dfoderick, thanks for the support!

At the current state I only wrote the bootloader so that it boots on the TI-84 Plus calculator. Unfortunately, due to the RSA encryption used to sign ROMs, it is not possible to flash a TI-84 Plus CE with a custom OS.

Currently it only works on a TI-84 Plus model.
